include "acceptor.conf"

persistence {
    store-type = "aeron"
    base-path = "./data/local-cache"
    aeron {
        media-driver { embedded = true, aeron-dir = "" }
        publisher-id = 1
        subscribers = [
            { name = "primary", host = "localhost", data-port = 40456, control-port = 40457 }
        ]
        local-endpoint { host = "0.0.0.0", replay-port = 40458 }
        replay { timeout-ms = 30000, max-batch-size = 10000 }
        heartbeat-interval-ms = 1000
        idle-strategy = "sleeping"
    }
}
