aeron-remote-store {
    base-path = "./data/remote-store"
    aeron {
        media-driver { embedded = true, aeron-dir = "" }
        listen { host = "0.0.0.0", data-port = 40456, control-port = 40457 }
        engines = [
            { name = "engine-1", host = "localhost", replay-port = 40458, publisher-id = 1 }
        ]
        idle-strategy = "sleeping"
        fragment-limit = 256
    }
}
